# This is a basic workflow to help you get started with Actions

name: 'Netlify Deploy'

# Controls when the workflow will run
on:
  push:
    branches: 
      - main
      
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
  
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          
      - run: npm install
      - run: npm run serve
      - run: npm run build --if-present
          
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
      
